apiVersion: v1
kind: Service
metadata:
  name: micro-opiniones-service
spec:
  type: LoadBalancer
  selector:
    app: micro-opiniones
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30899